name: CI pipline Angular Build

on: push

jobs:
  Build_Test_Build_docker_image:
      runs-on: ubuntu-latest
      permissions:
        contents: read
        packages: write

      steps:

        - uses: actions/checkout@v2
        - name: Use Node.js 14.x
          uses: actions/setup-node@v1
          with:
            node-version: 14.x

        - name: Setup
          run: npm ci
          
        - name: Test
          run: npm test -- --watch=false --browsers=ChromeHeadless

        - name: Ng build
          run: npm run build

        - name: Check out
          uses: actions/checkout@v2

        - name: Docker meta
          id: docker_meta
          uses: crazy-max/ghaction-docker-meta@v1
          with:
            images: ghcr.io/weberav/test-task
            tag-sha: true
            tag-edge: false
            tag-latest: true

        - name: Set up QEMU
          uses: docker/setup-qemu-action@v1

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1

        - name: Login to GHCR
          uses: docker/login-action@v1
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.TOKEN }}


        - name: Build image
          uses: docker/build-push-action@v2
          with:
            tags: ${{ steps.docker_meta.outputs.tags }} 
            file: ./Dockerfile

        - name: Push image
          uses: docker/build-push-action@v2
          with:
            push: true
            tags: ${{ steps.docker_meta.outputs.tags }}
            file: ./Dockerfile

        

